//
//  Scriptures.swift
//  FHE
//
//  Created by Rylan Evans on 12/21/17.
//  Copyright © 2017 Rylan Evans. All rights reserved.
//

import Foundation
import UIKit
import CoreData

func generateScripture() {
    getAllTasks()
    let scripture1 = Scripture(context: context)
    scripture1.topic = "Scriptures"
    scripture1.title = "Articles of Faith"
    scripture1.volume = "pgp"
    scripture1.book = "a-of-f"
    scripture1.chapter = 1
    scripture1.verse = ""
    scripture1.favorite = true
    scripture1.random = Int64(arc4random_uniform(1000))
    scripture1.selected = false
    scripture1.sortingIndex = 0
    scripture1.alphabet = String(describing: scripture1.title![(scripture1.title!.startIndex)])
    scripture1.order = Int64(defaultScriptureDictionary["\(scripture1.book!)"]!)
    
    let scripture2 = Scripture(context: context)
    scripture2.topic = "Resurrection"
    scripture2.title = "Resurrection through Christ"
    scripture2.volume = "nt"
    scripture2.book = "1-cor"
    scripture2.chapter = 15
    scripture2.verse = "20-22"
    scripture2.favorite = false
    scripture2.random = Int64(arc4random_uniform(1000))
    scripture2.selected = false
    scripture2.sortingIndex = 0
    scripture2.alphabet = String(describing: scripture2.title![(scripture2.title!.startIndex)])
    scripture2.order = Int64(defaultScriptureDictionary["\(scripture2.book!)"]!)
    
    let scripture3 = Scripture(context: context)
    scripture3.topic = "Plan of Salvation"
    scripture3.title = "Degrees of Heaven"
    scripture3.volume = "nt"
    scripture3.book = "1-cor"
    scripture3.chapter = 15
    scripture3.verse = "40-42"
    scripture3.favorite = false
    scripture3.random = Int64(arc4random_uniform(1000))
    scripture3.selected = false
    scripture3.sortingIndex = 0
    scripture3.alphabet = String(describing: scripture3.title![(scripture3.title!.startIndex)])
    scripture3.order = Int64(defaultScriptureDictionary["\(scripture3.book!)"]!)
    
    let scripture4 = Scripture(context: context)
    scripture4.topic = "Commandments"
    scripture4.title = "Your body is a temple"
    scripture4.volume = "nt"
    scripture4.book = "1-cor"
    scripture4.chapter = 6
    scripture4.verse = "19-20"
    scripture4.favorite = false
    scripture4.random = Int64(arc4random_uniform(1000))
    scripture4.selected = false
    scripture4.sortingIndex = 0
    scripture4.alphabet = String(describing: scripture4.title![(scripture4.title!.startIndex)])
    scripture4.order = Int64(defaultScriptureDictionary["\(scripture4.book!)"]!)
    
    let scripture5 = Scripture(context: context)
    scripture5.topic = "Commandments"
    scripture5.title = "Faith to do what is commanded"
    scripture5.volume = "bofm"
    scripture5.book = "1-ne"
    scripture5.chapter = 3
    scripture5.verse = "7"
    scripture5.favorite = true
    scripture5.random = Int64(arc4random_uniform(1000))
    scripture5.selected = false
    scripture5.sortingIndex = 0
    scripture5.alphabet = String(describing: scripture5.title![(scripture5.title!.startIndex)])
    scripture5.order = Int64(defaultScriptureDictionary["\(scripture5.book!)"]!)
    
    let scripture6 = Scripture(context: context)
    scripture6.topic = "Redeem the Dead"
    scripture6.title = "Preached to the dead"
    scripture6.volume = "nt"
    scripture6.book = "1-pet"
    scripture6.chapter = 4
    scripture6.verse = "6"
    scripture6.favorite = false
    scripture6.random = Int64(arc4random_uniform(1000))
    scripture6.selected = false
    scripture6.sortingIndex = 0
    scripture6.alphabet = String(describing: scripture6.title![(scripture6.title!.startIndex)])
    scripture6.order = Int64(defaultScriptureDictionary["\(scripture6.book!)"]!)
    
    let scripture7 = Scripture(context: context)
    scripture7.topic = "Christlike Attributes"
    scripture7.title = "Lord looketh on the heart"
    scripture7.volume = "ot"
    scripture7.book = "1-sam"
    scripture7.chapter = 16
    scripture7.verse = "7"
    scripture7.favorite = true
    scripture7.random = Int64(arc4random_uniform(1000))
    scripture7.selected = false
    scripture7.sortingIndex = 0
    scripture7.alphabet = String(describing: scripture7.title![(scripture7.title!.startIndex)])
    scripture7.order = Int64(defaultScriptureDictionary["\(scripture7.book!)"]!)
    
    let scripture8 = Scripture(context: context)
    scripture8.topic = "Plan of Salvation"
    scripture8.title = "Men might be"
    scripture8.volume = "bofm"
    scripture8.book = "2-ne"
    scripture8.chapter = 2
    scripture8.verse = "25"
    scripture8.favorite = false
    scripture8.random = Int64(arc4random_uniform(1000))
    scripture8.selected = false
    scripture8.sortingIndex = 0
    scripture8.alphabet = String(describing: scripture8.title![(scripture8.title!.startIndex)])
    scripture8.order = Int64(defaultScriptureDictionary["\(scripture8.book!)"]!)
    
    let scripture9 = Scripture(context: context)
    scripture9.topic = "Plan of Salvation"
    scripture9.title = "Free to choose"
    scripture9.volume = "bofm"
    scripture9.book = "2-ne"
    scripture9.chapter = 2
    scripture9.verse = "27"
    scripture9.favorite = true
    scripture9.random = Int64(arc4random_uniform(1000))
    scripture9.selected = false
    scripture9.sortingIndex = 0
    scripture9.alphabet = String(describing: scripture9.title![(scripture9.title!.startIndex)])
    scripture9.order = Int64(defaultScriptureDictionary["\(scripture9.book!)"]!)
    
    let scripture10 = Scripture(context: context)
    scripture10.topic = "Atonement"
    scripture10.title = "Grace that we are saved"
    scripture10.volume = "bofm"
    scripture10.book = "2-ne"
    scripture10.chapter = 25
    scripture10.verse = "23-26"
    scripture10.favorite = true
    scripture10.random = Int64(arc4random_uniform(1000))
    scripture10.selected = false
    scripture10.sortingIndex = 0
    scripture10.alphabet = String(describing: scripture10.title![(scripture10.title!.startIndex)])
    scripture10.order = Int64(defaultScriptureDictionary["\(scripture10.book!)"]!)
    
    let scripture11 = Scripture(context: context)
    scripture11.topic = "Scriptures"
    scripture11.title = "False, vain, and foolish doctrines"
    scripture11.volume = "bofm"
    scripture11.book = "2-ne"
    scripture11.chapter = 28
    scripture11.verse = "7-9"
    scripture11.favorite = false
    scripture11.random = Int64(arc4random_uniform(1000))
    scripture11.selected = false
    scripture11.sortingIndex = 0
    scripture11.alphabet = String(describing: scripture11.title![(scripture11.title!.startIndex)])
    scripture11.order = Int64(defaultScriptureDictionary["\(scripture11.book!)"]!)
    
    let scripture12 = Scripture(context: context)
    scripture12.topic = "Endure to the end"
    scripture12.title = "Endure to the End"
    scripture12.volume = "bofm"
    scripture12.book = "2-ne"
    scripture12.chapter = 31
    scripture12.verse = "19-20"
    scripture12.favorite = false
    scripture12.random = Int64(arc4random_uniform(1000))
    scripture12.selected = false
    scripture12.sortingIndex = 0
    scripture12.alphabet = String(describing: scripture12.title![(scripture12.title!.startIndex)])
    scripture12.order = Int64(defaultScriptureDictionary["\(scripture12.book!)"]!)
    
    let scripture13 = Scripture(context: context)
    scripture13.topic = "Scriptures"
    scripture13.title = "Words of Christ"
    scripture13.volume = "bofm"
    scripture13.book = "2-ne"
    scripture13.chapter = 32
    scripture13.verse = "3"
    scripture13.favorite = false
    scripture13.random = Int64(arc4random_uniform(1000))
    scripture13.selected = false
    scripture13.sortingIndex = 0
    scripture13.alphabet = String(describing: scripture13.title![(scripture13.title!.startIndex)])
    scripture13.order = Int64(defaultScriptureDictionary["\(scripture13.book!)"]!)
    
    let scripture14 = Scripture(context: context)
    scripture14.topic = "Holy Ghost"
    scripture14.title = "Spirit teaches us to pray"
    scripture14.volume = "bofm"
    scripture14.book = "2-ne"
    scripture14.chapter = 32
    scripture14.verse = "8-9"
    scripture14.favorite = false
    scripture14.random = Int64(arc4random_uniform(1000))
    scripture14.selected = false
    scripture14.sortingIndex = 0
    scripture14.alphabet = String(describing: scripture14.title![(scripture14.title!.startIndex)])
    scripture14.order = Int64(defaultScriptureDictionary["\(scripture14.book!)"]!)
    
    let scripture15 = Scripture(context: context)
    scripture15.topic = "Christlike Attributes"
    scripture15.title = "Hearken to the counsels of God"
    scripture15.volume = "bofm"
    scripture15.book = "2-ne"
    scripture15.chapter = 9
    scripture15.verse = "28-29"
    scripture15.favorite = false
    scripture15.random = Int64(arc4random_uniform(1000))
    scripture15.selected = false
    scripture15.sortingIndex = 0
    scripture15.alphabet = String(describing: scripture15.title![(scripture15.title!.startIndex)])
    scripture15.order = Int64(defaultScriptureDictionary["\(scripture15.book!)"]!)
    
    let scripture16 = Scripture(context: context)
    scripture16.topic = "Restoration"
    scripture16.title = "Falling away"
    scripture16.volume = "nt"
    scripture16.book = "2-thes"
    scripture16.chapter = 2
    scripture16.verse = "1-3"
    scripture16.favorite = false
    scripture16.random = Int64(arc4random_uniform(1000))
    scripture16.selected = false
    scripture16.sortingIndex = 0
    scripture16.alphabet = String(describing: scripture16.title![(scripture16.title!.startIndex)])
    scripture16.order = Int64(defaultScriptureDictionary["\(scripture16.book!)"]!)
    
    let scripture17 = Scripture(context: context)
    scripture17.topic = "Scriptures"
    scripture17.title = "Scripture is given by God"
    scripture17.volume = "nt"
    scripture17.book = "2-tim"
    scripture17.chapter = 3
    scripture17.verse = "15-17"
    scripture17.favorite = false
    scripture17.random = Int64(arc4random_uniform(1000))
    scripture17.selected = false
    scripture17.sortingIndex = 0
    scripture17.alphabet = String(describing: scripture17.title![(scripture17.title!.startIndex)])
    scripture17.order = Int64(defaultScriptureDictionary["\(scripture17.book!)"]!)
    
    let scripture18 = Scripture(context: context)
    scripture18.topic = "Jesus Christ"
    scripture18.title = "Be perfect even as I"
    scripture18.volume = "bofm"
    scripture18.book = "3-ne"
    scripture18.chapter = 12
    scripture18.verse = "48"
    scripture18.favorite = false
    scripture18.random = Int64(arc4random_uniform(1000))
    scripture18.selected = false
    scripture18.sortingIndex = 0
    scripture18.alphabet = String(describing: scripture18.title![(scripture18.title!.startIndex)])
    scripture18.order = Int64(defaultScriptureDictionary["\(scripture18.book!)"]!)
    
    let scripture19 = Scripture(context: context)
    scripture19.topic = "Endure to the end"
    scripture19.title = "Pray always"
    scripture19.volume = "bofm"
    scripture19.book = "3-ne"
    scripture19.chapter = 18
    scripture19.verse = "15-21"
    scripture19.favorite = false
    scripture19.random = Int64(arc4random_uniform(1000))
    scripture19.selected = false
    scripture19.sortingIndex = 0
    scripture19.alphabet = String(describing: scripture19.title![(scripture19.title!.startIndex)])
    scripture19.order = Int64(defaultScriptureDictionary["\(scripture19.book!)"]!)
    
    let scripture20 = Scripture(context: context)
    scripture20.topic = "Plan of Salvation"
    scripture20.title = "Noble and great spirits"
    scripture20.volume = "pgp"
    scripture20.book = "abr"
    scripture20.chapter = 3
    scripture20.verse = "22-23"
    scripture20.favorite = false
    scripture20.random = Int64(arc4random_uniform(1000))
    scripture20.selected = false
    scripture20.sortingIndex = 0
    scripture20.alphabet = String(describing: scripture20.title![(scripture20.title!.startIndex)])
    scripture20.order = Int64(defaultScriptureDictionary["\(scripture20.book!)"]!)
    
    let scripture21 = Scripture(context: context)
    scripture21.topic = "Principles & Ordinances"
    scripture21.title = "Repent, be baptized, and receive the gift of the Holy Ghost"
    scripture21.volume = "nt"
    scripture21.book = "acts"
    scripture21.chapter = 2
    scripture21.verse = "36-38"
    scripture21.favorite = false
    scripture21.random = Int64(arc4random_uniform(1000))
    scripture21.selected = false
    scripture21.sortingIndex = 0
    scripture21.alphabet = String(describing: scripture21.title![(scripture21.title!.startIndex)])
    scripture21.order = Int64(defaultScriptureDictionary["\(scripture21.book!)"]!)
    
    let scripture22 = Scripture(context: context)
    scripture22.topic = "Restoration"
    scripture22.title = "Restitution of all things"
    scripture22.volume = "nt"
    scripture22.book = "acts"
    scripture22.chapter = 3
    scripture22.verse = "19-21"
    scripture22.favorite = false
    scripture22.random = Int64(arc4random_uniform(1000))
    scripture22.selected = false
    scripture22.sortingIndex = 0
    scripture22.alphabet = String(describing: scripture22.title![(scripture22.title!.startIndex)])
    scripture22.order = Int64(defaultScriptureDictionary["\(scripture22.book!)"]!)
    
    let scripture23 = Scripture(context: context)
    scripture23.topic = "Principles & Ordinances"
    scripture23.title = "Faith"
    scripture23.volume = "bofm"
    scripture23.book = "alma"
    scripture23.chapter = 32
    scripture23.verse = "21"
    scripture23.favorite = false
    scripture23.random = Int64(arc4random_uniform(1000))
    scripture23.selected = false
    scripture23.sortingIndex = 0
    scripture23.alphabet = String(describing: scripture23.title![(scripture23.title!.startIndex)])
    scripture23.order = Int64(defaultScriptureDictionary["\(scripture23.book!)"]!)
    
    let scripture24 = Scripture(context: context)
    scripture24.topic = "Commandments"
    scripture24.title = "Learn in thy youth"
    scripture24.volume = "bofm"
    scripture24.book = "alma"
    scripture24.chapter = 37
    scripture24.verse = "35"
    scripture24.favorite = false
    scripture24.random = Int64(arc4random_uniform(1000))
    scripture24.selected = false
    scripture24.sortingIndex = 0
    scripture24.alphabet = String(describing: scripture24.title![(scripture24.title!.startIndex)])
    scripture24.order = Int64(defaultScriptureDictionary["\(scripture24.book!)"]!)
    
    let scripture25 = Scripture(context: context)
    scripture25.topic = "Commandments"
    scripture25.title = "Lust"
    scripture25.volume = "bofm"
    scripture25.book = "alma"
    scripture25.chapter = 39
    scripture25.verse = "9"
    scripture25.favorite = false
    scripture25.random = Int64(arc4random_uniform(1000))
    scripture25.selected = false
    scripture25.sortingIndex = 0
    scripture25.alphabet = String(describing: scripture25.title![(scripture25.title!.startIndex)])
    scripture25.order = Int64(defaultScriptureDictionary["\(scripture25.book!)"]!)
    
    let scripture26 = Scripture(context: context)
    scripture26.topic = "Endure to the end"
    scripture26.title = "Wickedness never was happiness"
    scripture26.volume = "bofm"
    scripture26.book = "alma"
    scripture26.chapter = 41
    scripture26.verse = "10"
    scripture26.favorite = false
    scripture26.random = Int64(arc4random_uniform(1000))
    scripture26.selected = false
    scripture26.sortingIndex = 0
    scripture26.alphabet = String(describing: scripture26.title![(scripture26.title!.startIndex)])
    scripture26.order = Int64(defaultScriptureDictionary["\(scripture26.book!)"]!)
    
    let scripture27 = Scripture(context: context)
    scripture27.topic = "Atonement"
    scripture27.title = "Overcame sin and death"
    scripture27.volume = "bofm"
    scripture27.book = "alma"
    scripture27.chapter = 7
    scripture27.verse = "11-13"
    scripture27.favorite = false
    scripture27.random = Int64(arc4random_uniform(1000))
    scripture27.selected = false
    scripture27.sortingIndex = 0
    scripture27.alphabet = String(describing: scripture27.title![(scripture27.title!.startIndex)])
    scripture27.order = Int64(defaultScriptureDictionary["\(scripture27.book!)"]!)
    
    let scripture28 = Scripture(context: context)
    scripture28.topic = "Restoration"
    scripture28.title = "God reveals His secrets"
    scripture28.volume = "ot"
    scripture28.book = "amos"
    scripture28.chapter = 3
    scripture28.verse = "7"
    scripture28.favorite = false
    scripture28.random = Int64(arc4random_uniform(1000))
    scripture28.selected = false
    scripture28.sortingIndex = 0
    scripture28.alphabet = String(describing: scripture28.title![(scripture28.title!.startIndex)])
    scripture28.order = Int64(defaultScriptureDictionary["\(scripture28.book!)"]!)
    
    let scripture29 = Scripture(context: context)
    scripture29.topic = "Scriptures"
    scripture29.title = "Christ’s words shall all be fulfilled"
    scripture29.volume = "dc-testament"
    scripture29.book = "dc"
    scripture29.chapter = 1
    scripture29.verse = "37-38"
    scripture29.favorite = false
    scripture29.random = Int64(arc4random_uniform(1000))
    scripture29.selected = false
    scripture29.sortingIndex = 0
    scripture29.alphabet = String(describing: scripture29.title![(scripture29.title!.startIndex)])
    scripture29.order = Int64(defaultScriptureDictionary["\(scripture29.book!)"]!)
    
    let scripture30 = Scripture(context: context)
    scripture30.topic = "Endure to the end"
    scripture30.title = "Pray always"
    scripture30.volume = "dc-testament"
    scripture30.book = "dc"
    scripture30.chapter = 10
    scripture30.verse = "5"
    scripture30.favorite = false
    scripture30.random = Int64(arc4random_uniform(1000))
    scripture30.selected = false
    scripture30.sortingIndex = 0
    scripture30.alphabet = String(describing: scripture30.title![(scripture30.title!.startIndex)])
    scripture30.order = Int64(defaultScriptureDictionary["\(scripture30.book!)"]!)
    
    let scripture31 = Scripture(context: context)
    scripture31.topic = "Restoration"
    scripture31.title = "Melchizedek Priesthood"
    scripture31.volume = "dc-testament"
    scripture31.book = "dc"
    scripture31.chapter = 107
    scripture31.verse = "8"
    scripture31.favorite = false
    scripture31.random = Int64(arc4random_uniform(1000))
    scripture31.selected = false
    scripture31.sortingIndex = 0
    scripture31.alphabet = String(describing: scripture31.title![(scripture31.title!.startIndex)])
    scripture31.order = Int64(defaultScriptureDictionary["\(scripture31.book!)"]!)
    
    let scripture32 = Scripture(context: context)
    scripture32.topic = "Restoration"
    scripture32.title = "Rights of the priesthood"
    scripture32.volume = "dc-testament"
    scripture32.book = "dc"
    scripture32.chapter = 121
    scripture32.verse = "36-42"
    scripture32.favorite = false
    scripture32.random = Int64(arc4random_uniform(1000))
    scripture32.selected = false
    scripture32.sortingIndex = 0
    scripture32.alphabet = String(describing: scripture32.title![(scripture32.title!.startIndex)])
    scripture32.order = Int64(defaultScriptureDictionary["\(scripture32.book!)"]!)
    
    let scripture33 = Scripture(context: context)
    scripture33.topic = "Restoration"
    scripture33.title = "The Aaronic Priesthood Keys"
    scripture33.volume = "dc-testament"
    scripture33.book = "dc"
    scripture33.chapter = 13
    scripture33.verse = "1"
    scripture33.favorite = false
    scripture33.random = Int64(arc4random_uniform(1000))
    scripture33.selected = false
    scripture33.sortingIndex = 0
    scripture33.alphabet = String(describing: scripture33.title![(scripture33.title!.startIndex)])
    scripture33.order = Int64(defaultScriptureDictionary["\(scripture33.book!)"]!)
    
    let scripture34 = Scripture(context: context)
    scripture34.topic = "Plan of Salvation"
    scripture34.title = "God, Jesus, and Holy Ghost Souls"
    scripture34.volume = "dc-testament"
    scripture34.book = "dc"
    scripture34.chapter = 130
    scripture34.verse = "22-23"
    scripture34.favorite = false
    scripture34.random = Int64(arc4random_uniform(1000))
    scripture34.selected = false
    scripture34.sortingIndex = 0
    scripture34.alphabet = String(describing: scripture34.title![(scripture34.title!.startIndex)])
    scripture34.order = Int64(defaultScriptureDictionary["\(scripture34.book!)"]!)
    
    let scripture35 = Scripture(context: context)
    scripture35.topic = "Plan of Salvation"
    scripture35.title = "Everlasting covenant of marriage"
    scripture35.volume = "dc-testament"
    scripture35.book = "dc"
    scripture35.chapter = 131
    scripture35.verse = "1-4"
    scripture35.favorite = false
    scripture35.random = Int64(arc4random_uniform(1000))
    scripture35.selected = false
    scripture35.sortingIndex = 0
    scripture35.alphabet = String(describing: scripture35.title![(scripture35.title!.startIndex)])
    scripture35.order = Int64(defaultScriptureDictionary["\(scripture35.book!)"]!)
    
    let scripture36 = Scripture(context: context)
    scripture36.topic = "Heavenly Father"
    scripture36.title = "Worth of souls is great"
    scripture36.volume = "dc-testament"
    scripture36.book = "dc"
    scripture36.chapter = 18
    scripture36.verse = "10-11"
    scripture36.favorite = false
    scripture36.random = Int64(arc4random_uniform(1000))
    scripture36.selected = false
    scripture36.sortingIndex = 0
    scripture36.alphabet = String(describing: scripture36.title![(scripture36.title!.startIndex)])
    scripture36.order = Int64(defaultScriptureDictionary["\(scripture36.book!)"]!)
    
    let scripture37 = Scripture(context: context)
    scripture37.topic = "Proclaim the Gospel"
    scripture37.title = "Bring souls unto Jesus Christ"
    scripture37.volume = "dc-testament"
    scripture37.book = "dc"
    scripture37.chapter = 18
    scripture37.verse = "15-16"
    scripture37.favorite = false
    scripture37.random = Int64(arc4random_uniform(1000))
    scripture37.selected = false
    scripture37.sortingIndex = 0
    scripture37.alphabet = String(describing: scripture37.title![(scripture37.title!.startIndex)])
    scripture37.order = Int64(defaultScriptureDictionary["\(scripture37.book!)"]!)
    
    let scripture38 = Scripture(context: context)
    scripture38.topic = "Atonement"
    scripture38.title = "Jesus Christ suffered for all"
    scripture38.volume = "dc-testament"
    scripture38.book = "dc"
    scripture38.chapter = 19
    scripture38.verse = "16-19"
    scripture38.favorite = false
    scripture38.random = Int64(arc4random_uniform(1000))
    scripture38.selected = false
    scripture38.sortingIndex = 0
    scripture38.alphabet = String(describing: scripture38.title![(scripture38.title!.startIndex)])
    scripture38.order = Int64(defaultScriptureDictionary["\(scripture38.book!)"]!)
    
    let scripture39 = Scripture(context: context)
    scripture39.topic = "Jesus Christ"
    scripture39.title = "You shall have peace in Him"
    scripture39.volume = "dc-testament"
    scripture39.book = "dc"
    scripture39.chapter = 19
    scripture39.verse = "23"
    scripture39.favorite = false
    scripture39.random = Int64(arc4random_uniform(1000))
    scripture39.selected = false
    scripture39.sortingIndex = 0
    scripture39.alphabet = String(describing: scripture39.title![(scripture39.title!.startIndex)])
    scripture39.order = Int64(defaultScriptureDictionary["\(scripture39.book!)"]!)
    
    let scripture40 = Scripture(context: context)
    scripture40.topic = "Commandments"
    scripture40.title = "Cleave unto the covenants"
    scripture40.volume = "dc-testament"
    scripture40.book = "dc"
    scripture40.chapter = 25
    scripture40.verse = "13"
    scripture40.favorite = false
    scripture40.random = Int64(arc4random_uniform(1000))
    scripture40.selected = false
    scripture40.sortingIndex = 0
    scripture40.alphabet = String(describing: scripture40.title![(scripture40.title!.startIndex)])
    scripture40.order = Int64(defaultScriptureDictionary["\(scripture40.book!)"]!)
    
    let scripture41 = Scripture(context: context)
    scripture41.topic = "Christlike Attributes"
    scripture41.title = "Practice virtue and holiness"
    scripture41.volume = "dc-testament"
    scripture41.book = "dc"
    scripture41.chapter = 46
    scripture41.verse = "33"
    scripture41.favorite = true
    scripture41.random = Int64(arc4random_uniform(1000))
    scripture41.selected = false
    scripture41.sortingIndex = 0
    scripture41.alphabet = String(describing: scripture41.title![(scripture41.title!.startIndex)])
    scripture41.order = Int64(defaultScriptureDictionary["\(scripture41.book!)"]!)
    
    let scripture42 = Scripture(context: context)
    scripture42.topic = "Christlike Attributes"
    scripture42.title = "Engaged in a good cause"
    scripture42.volume = "dc-testament"
    scripture42.book = "dc"
    scripture42.chapter = 58
    scripture42.verse = "27"
    scripture42.favorite = true
    scripture42.random = Int64(arc4random_uniform(1000))
    scripture42.selected = false
    scripture42.sortingIndex = 0
    scripture42.alphabet = String(describing: scripture42.title![(scripture42.title!.startIndex)])
    scripture42.order = Int64(defaultScriptureDictionary["\(scripture42.book!)"]!)
    
    let scripture43 = Scripture(context: context)
    scripture43.topic = "Principles & Ordinances"
    scripture43.title = "Repent of sins"
    scripture43.volume = "dc-testament"
    scripture43.book = "dc"
    scripture43.chapter = 58
    scripture43.verse = "42-43"
    scripture43.favorite = false
    scripture43.random = Int64(arc4random_uniform(1000))
    scripture43.selected = false
    scripture43.sortingIndex = 0
    scripture43.alphabet = String(describing: scripture43.title![(scripture43.title!.startIndex)])
    scripture43.order = Int64(defaultScriptureDictionary["\(scripture43.book!)"]!)
    
    let scripture44 = Scripture(context: context)
    scripture44.topic = "Jesus Christ"
    scripture44.title = "Doubt not, fear not"
    scripture44.volume = "dc-testament"
    scripture44.book = "dc"
    scripture44.chapter = 6
    scripture44.verse = "36"
    scripture44.favorite = false
    scripture44.random = Int64(arc4random_uniform(1000))
    scripture44.selected = false
    scripture44.sortingIndex = 0
    scripture44.alphabet = String(describing: scripture44.title![(scripture44.title!.startIndex)])
    scripture44.order = Int64(defaultScriptureDictionary["\(scripture44.book!)"]!)
    
    let scripture45 = Scripture(context: context)
    scripture45.topic = "Forgiveness"
    scripture45.title = "Forgive all men"
    scripture45.volume = "dc-testament"
    scripture45.book = "dc"
    scripture45.chapter = 64
    scripture45.verse = "9-11"
    scripture45.favorite = false
    scripture45.random = Int64(arc4random_uniform(1000))
    scripture45.selected = false
    scripture45.sortingIndex = 0
    scripture45.alphabet = String(describing: scripture45.title![(scripture45.title!.startIndex)])
    scripture45.order = Int64(defaultScriptureDictionary["\(scripture45.book!)"]!)
    
    let scripture46 = Scripture(context: context)
    scripture46.topic = "Jesus Christ"
    scripture46.title = "Testified that He lives"
    scripture46.volume = "dc-testament"
    scripture46.book = "dc"
    scripture46.chapter = 76
    scripture46.verse = "22-24"
    scripture46.favorite = false
    scripture46.random = Int64(arc4random_uniform(1000))
    scripture46.selected = false
    scripture46.sortingIndex = 0
    scripture46.alphabet = String(describing: scripture46.title![(scripture46.title!.startIndex)])
    scripture46.order = Int64(defaultScriptureDictionary["\(scripture46.book!)"]!)
    
    let scripture47 = Scripture(context: context)
    scripture47.topic = "Atonement"
    scripture47.title = "Cleanse the world"
    scripture47.volume = "dc-testament"
    scripture47.book = "dc"
    scripture47.chapter = 76
    scripture47.verse = "40-41"
    scripture47.favorite = false
    scripture47.random = Int64(arc4random_uniform(1000))
    scripture47.selected = false
    scripture47.sortingIndex = 0
    scripture47.alphabet = String(describing: scripture47.title![(scripture47.title!.startIndex)])
    scripture47.order = Int64(defaultScriptureDictionary["\(scripture47.book!)"]!)
    
    let scripture48 = Scripture(context: context)
    scripture48.topic = "Christlike Attributes"
    scripture48.title = "Thankfulness will be blessed"
    scripture48.volume = "dc-testament"
    scripture48.book = "dc"
    scripture48.chapter = 78
    scripture48.verse = "19"
    scripture48.favorite = true
    scripture48.random = Int64(arc4random_uniform(1000))
    scripture48.selected = false
    scripture48.sortingIndex = 0
    scripture48.alphabet = String(describing: scripture48.title![(scripture48.title!.startIndex)])
    scripture48.order = Int64(defaultScriptureDictionary["\(scripture48.book!)"]!)
    
    let scripture49 = Scripture(context: context)
    scripture49.topic = "Holy Ghost"
    scripture49.title = "Holy Ghost reveals truth"
    scripture49.volume = "dc-testament"
    scripture49.book = "dc"
    scripture49.chapter = 8
    scripture49.verse = "2-3"
    scripture49.favorite = false
    scripture49.random = Int64(arc4random_uniform(1000))
    scripture49.selected = false
    scripture49.sortingIndex = 0
    scripture49.alphabet = String(describing: scripture49.title![(scripture49.title!.startIndex)])
    scripture49.order = Int64(defaultScriptureDictionary["\(scripture49.book!)"]!)
    
    let scripture50 = Scripture(context: context)
    scripture50.topic = "Christlike Attributes"
    scripture50.title = "Obedience"
    scripture50.volume = "dc-testament"
    scripture50.book = "dc"
    scripture50.chapter = 82
    scripture50.verse = "10"
    scripture50.favorite = true
    scripture50.random = Int64(arc4random_uniform(1000))
    scripture50.selected = false
    scripture50.sortingIndex = 0
    scripture50.alphabet = String(describing: scripture50.title![(scripture50.title!.startIndex)])
    scripture50.order = Int64(defaultScriptureDictionary["\(scripture50.book!)"]!)
    
    let scripture51 = Scripture(context: context)
    scripture51.topic = "Christlike Attributes"
    scripture51.title = "Cease to be idle"
    scripture51.volume = "dc-testament"
    scripture51.book = "dc"
    scripture51.chapter = 88
    scripture51.verse = "124"
    scripture51.favorite = false
    scripture51.random = Int64(arc4random_uniform(1000))
    scripture51.selected = false
    scripture51.sortingIndex = 0
    scripture51.alphabet = String(describing: scripture51.title![(scripture51.title!.startIndex)])
    scripture51.order = Int64(defaultScriptureDictionary["\(scripture51.book!)"]!)
    
    let scripture52 = Scripture(context: context)
    scripture52.topic = "Commandments"
    scripture52.title = "Word of Wisdom"
    scripture52.volume = "dc-testament"
    scripture52.book = "dc"
    scripture52.chapter = 89
    scripture52.verse = "18-21"
    scripture52.favorite = false
    scripture52.random = Int64(arc4random_uniform(1000))
    scripture52.selected = false
    scripture52.sortingIndex = 0
    scripture52.alphabet = String(describing: scripture52.title![(scripture52.title!.startIndex)])
    scripture52.order = Int64(defaultScriptureDictionary["\(scripture52.book!)"]!)
    
    let scripture53 = Scripture(context: context)
    scripture53.topic = "Restoration"
    scripture53.title = "Prophets & Apostles"
    scripture53.volume = "nt"
    scripture53.book = "eph"
    scripture53.chapter = 4
    scripture53.verse = "11-14"
    scripture53.favorite = false
    scripture53.random = Int64(arc4random_uniform(1000))
    scripture53.selected = false
    scripture53.sortingIndex = 0
    scripture53.alphabet = String(describing: scripture53.title![(scripture53.title!.startIndex)])
    scripture53.order = Int64(defaultScriptureDictionary["\(scripture53.book!)"]!)
    
    let scripture54 = Scripture(context: context)
    scripture54.topic = "Jesus Christ"
    scripture54.title = "Weak things become strong"
    scripture54.volume = "bofm"
    scripture54.book = "ether"
    scripture54.chapter = 12
    scripture54.verse = "27"
    scripture54.favorite = true
    scripture54.random = Int64(arc4random_uniform(1000))
    scripture54.selected = false
    scripture54.sortingIndex = 0
    scripture54.alphabet = String(describing: scripture54.title![(scripture54.title!.startIndex)])
    scripture54.order = Int64(defaultScriptureDictionary["\(scripture54.book!)"]!)
    
    let scripture55 = Scripture(context: context)
    scripture55.topic = "Endure to the end"
    scripture55.title = "No witness until after"
    scripture55.volume = "bofm"
    scripture55.book = "ether"
    scripture55.chapter = 12
    scripture55.verse = "6"
    scripture55.favorite = false
    scripture55.random = Int64(arc4random_uniform(1000))
    scripture55.selected = false
    scripture55.sortingIndex = 0
    scripture55.alphabet = String(describing: scripture55.title![(scripture55.title!.startIndex)])
    scripture55.order = Int64(defaultScriptureDictionary["\(scripture55.book!)"]!)
    
    let scripture56 = Scripture(context: context)
    scripture56.topic = "Commandments"
    scripture56.title = "Keep my covenant"
    scripture56.volume = "ot"
    scripture56.book = "ex"
    scripture56.chapter = 19
    scripture56.verse = "5-6"
    scripture56.favorite = false
    scripture56.random = Int64(arc4random_uniform(1000))
    scripture56.selected = false
    scripture56.sortingIndex = 0
    scripture56.alphabet = String(describing: scripture56.title![(scripture56.title!.startIndex)])
    scripture56.order = Int64(defaultScriptureDictionary["\(scripture56.book!)"]!)
    
    let scripture57 = Scripture(context: context)
    scripture57.topic = "Commandments"
    scripture57.title = "The Ten Commandments"
    scripture57.volume = "ot"
    scripture57.book = "ex"
    scripture57.chapter = 20
    scripture57.verse = "3-17"
    scripture57.favorite = false
    scripture57.random = Int64(arc4random_uniform(1000))
    scripture57.selected = false
    scripture57.sortingIndex = 0
    scripture57.alphabet = String(describing: scripture57.title![(scripture57.title!.startIndex)])
    scripture57.order = Int64(defaultScriptureDictionary["\(scripture57.book!)"]!)
    
    let scripture58 = Scripture(context: context)
    scripture58.topic = "Restoration"
    scripture58.title = "The stick of Judah"
    scripture58.volume = "ot"
    scripture58.book = "ezek"
    scripture58.chapter = 37
    scripture58.verse = "15-17"
    scripture58.favorite = false
    scripture58.random = Int64(arc4random_uniform(1000))
    scripture58.selected = false
    scripture58.sortingIndex = 0
    scripture58.alphabet = String(describing: scripture58.title![(scripture58.title!.startIndex)])
    scripture58.order = Int64(defaultScriptureDictionary["\(scripture58.book!)"]!)
    
    let scripture59 = Scripture(context: context)
    scripture59.topic = "Holy Ghost"
    scripture59.title = "Fruit of the Spirit"
    scripture59.volume = "nt"
    scripture59.book = "gal"
    scripture59.chapter = 5
    scripture59.verse = "22-23"
    scripture59.favorite = true
    scripture59.random = Int64(arc4random_uniform(1000))
    scripture59.selected = false
    scripture59.sortingIndex = 0
    scripture59.alphabet = String(describing: scripture59.title![(scripture59.title!.startIndex)])
    scripture59.order = Int64(defaultScriptureDictionary["\(scripture59.book!)"]!)
    
    let scripture60 = Scripture(context: context)
    scripture60.topic = "Heavenly Father"
    scripture60.title = "His own image"
    scripture60.volume = "ot"
    scripture60.book = "gen"
    scripture60.chapter = 1
    scripture60.verse = "26-27"
    scripture60.favorite = false
    scripture60.random = Int64(arc4random_uniform(1000))
    scripture60.selected = false
    scripture60.sortingIndex = 0
    scripture60.alphabet = String(describing: scripture60.title![(scripture60.title!.startIndex)])
    scripture60.order = Int64(defaultScriptureDictionary["\(scripture60.book!)"]!)
    
    let scripture61 = Scripture(context: context)
    scripture61.topic = "Plan of Salvation"
    scripture61.title = "Husbands and wives are one"
    scripture61.volume = "ot"
    scripture61.book = "gen"
    scripture61.chapter = 2
    scripture61.verse = "24"
    scripture61.favorite = false
    scripture61.random = Int64(arc4random_uniform(1000))
    scripture61.selected = false
    scripture61.sortingIndex = 0
    scripture61.alphabet = String(describing: scripture61.title![(scripture61.title!.startIndex)])
    scripture61.order = Int64(defaultScriptureDictionary["\(scripture61.book!)"]!)
    
    let scripture62 = Scripture(context: context)
    scripture62.topic = "Commandments"
    scripture62.title = "Resist temptation"
    scripture62.volume = "ot"
    scripture62.book = "gen"
    scripture62.chapter = 39
    scripture62.verse = "9"
    scripture62.favorite = false
    scripture62.random = Int64(arc4random_uniform(1000))
    scripture62.selected = false
    scripture62.sortingIndex = 0
    scripture62.alphabet = String(describing: scripture62.title![(scripture62.title!.startIndex)])
    scripture62.order = Int64(defaultScriptureDictionary["\(scripture62.book!)"]!)
    
    let scripture63 = Scripture(context: context)
    scripture63.topic = "Heavenly Father"
    scripture63.title = "Subjection unto the Father"
    scripture63.volume = "nt"
    scripture63.book = "heb"
    scripture63.chapter = 12
    scripture63.verse = "9"
    scripture63.favorite = false
    scripture63.random = Int64(arc4random_uniform(1000))
    scripture63.selected = false
    scripture63.sortingIndex = 0
    scripture63.alphabet = String(describing: scripture63.title![(scripture63.title!.startIndex)])
    scripture63.order = Int64(defaultScriptureDictionary["\(scripture63.book!)"]!)
    
    let scripture64 = Scripture(context: context)
    scripture64.topic = "Jesus Christ"
    scripture64.title = "Rock of our Redeemer"
    scripture64.volume = "bofm"
    scripture64.book = "hel"
    scripture64.chapter = 5
    scripture64.verse = "12"
    scripture64.favorite = false
    scripture64.random = Int64(arc4random_uniform(1000))
    scripture64.selected = false
    scripture64.sortingIndex = 0
    scripture64.alphabet = String(describing: scripture64.title![(scripture64.title!.startIndex)])
    scripture64.order = Int64(defaultScriptureDictionary["\(scripture64.book!)"]!)
    
    let scripture65 = Scripture(context: context)
    scripture65.topic = "Atonement"
    scripture65.title = "Sins white as snow"
    scripture65.volume = "ot"
    scripture65.book = "isa"
    scripture65.chapter = 1
    scripture65.verse = "18"
    scripture65.favorite = true
    scripture65.random = Int64(arc4random_uniform(1000))
    scripture65.selected = false
    scripture65.sortingIndex = 0
    scripture65.alphabet = String(describing: scripture65.title![(scripture65.title!.startIndex)])
    scripture65.order = Int64(defaultScriptureDictionary["\(scripture65.book!)"]!)
    
    let scripture66 = Scripture(context: context)
    scripture66.topic = "Restoration"
    scripture66.title = "Marvelous work and a wonder"
    scripture66.volume = "ot"
    scripture66.book = "isa"
    scripture66.chapter = 29
    scripture66.verse = "13-14"
    scripture66.favorite = false
    scripture66.random = Int64(arc4random_uniform(1000))
    scripture66.selected = false
    scripture66.sortingIndex = 0
    scripture66.alphabet = String(describing: scripture66.title![(scripture66.title!.startIndex)])
    scripture66.order = Int64(defaultScriptureDictionary["\(scripture66.book!)"]!)
    
    let scripture67 = Scripture(context: context)
    scripture67.topic = "Endure to the end"
    scripture67.title = "Evil good, and good evil"
    scripture67.volume = "ot"
    scripture67.book = "isa"
    scripture67.chapter = 5
    scripture67.verse = "20"
    scripture67.favorite = false
    scripture67.random = Int64(arc4random_uniform(1000))
    scripture67.selected = false
    scripture67.sortingIndex = 0
    scripture67.alphabet = String(describing: scripture67.title![(scripture67.title!.startIndex)])
    scripture67.order = Int64(defaultScriptureDictionary["\(scripture67.book!)"]!)
    
    let scripture68 = Scripture(context: context)
    scripture68.topic = "Atonement"
    scripture68.title = "Griefs, sorrows, and transgressions"
    scripture68.volume = "ot"
    scripture68.book = "isa"
    scripture68.chapter = 53
    scripture68.verse = "3-5"
    scripture68.favorite = false
    scripture68.random = Int64(arc4random_uniform(1000))
    scripture68.selected = false
    scripture68.sortingIndex = 0
    scripture68.alphabet = String(describing: scripture68.title![(scripture68.title!.startIndex)])
    scripture68.order = Int64(defaultScriptureDictionary["\(scripture68.book!)"]!)
    
    let scripture69 = Scripture(context: context)
    scripture69.topic = "Commandments"
    scripture69.title = "Sabbath day"
    scripture69.volume = "ot"
    scripture69.book = "isa"
    scripture69.chapter = 58
    scripture69.verse = "13-14"
    scripture69.favorite = false
    scripture69.random = Int64(arc4random_uniform(1000))
    scripture69.selected = false
    scripture69.sortingIndex = 0
    scripture69.alphabet = String(describing: scripture69.title![(scripture69.title!.startIndex)])
    scripture69.order = Int64(defaultScriptureDictionary["\(scripture69.book!)"]!)
    
    let scripture70 = Scripture(context: context)
    scripture70.topic = "Principles & Ordinances"
    scripture70.title = "Fasting"
    scripture70.volume = "ot"
    scripture70.book = "isa"
    scripture70.chapter = 58
    scripture70.verse = "6-7"
    scripture70.favorite = false
    scripture70.random = Int64(arc4random_uniform(1000))
    scripture70.selected = false
    scripture70.sortingIndex = 0
    scripture70.alphabet = String(describing: scripture70.title![(scripture70.title!.startIndex)])
    scripture70.order = Int64(defaultScriptureDictionary["\(scripture70.book!)"]!)
    
    let scripture71 = Scripture(context: context)
    scripture71.topic = "Heavenly Father"
    scripture71.title = "Ask of God"
    scripture71.volume = "nt"
    scripture71.book = "james"
    scripture71.chapter = 1
    scripture71.verse = "5-6"
    scripture71.favorite = false
    scripture71.random = Int64(arc4random_uniform(1000))
    scripture71.selected = false
    scripture71.sortingIndex = 0
    scripture71.alphabet = String(describing: scripture71.title![(scripture71.title!.startIndex)])
    scripture71.order = Int64(defaultScriptureDictionary["\(scripture71.book!)"]!)
    
    let scripture72 = Scripture(context: context)
    scripture72.topic = "Principles & Ordinances"
    scripture72.title = "Faith without works"
    scripture72.volume = "nt"
    scripture72.book = "james"
    scripture72.chapter = 2
    scripture72.verse = "17-18"
    scripture72.favorite = false
    scripture72.random = Int64(arc4random_uniform(1000))
    scripture72.selected = false
    scripture72.sortingIndex = 0
    scripture72.alphabet = String(describing: scripture72.title![(scripture72.title!.startIndex)])
    scripture72.order = Int64(defaultScriptureDictionary["\(scripture72.book!)"]!)
    
    let scripture73 = Scripture(context: context)
    scripture73.topic = "Plan of Salvation"
    scripture73.title = "God knew us before birth"
    scripture73.volume = "ot"
    scripture73.book = "jer"
    scripture73.chapter = 1
    scripture73.verse = "4-5"
    scripture73.favorite = false
    scripture73.random = Int64(arc4random_uniform(1000))
    scripture73.selected = false
    scripture73.sortingIndex = 0
    scripture73.alphabet = String(describing: scripture73.title![(scripture73.title!.startIndex)])
    scripture73.order = Int64(defaultScriptureDictionary["\(scripture73.book!)"]!)
    
    let scripture74 = Scripture(context: context)
    scripture74.topic = "Commandments"
    scripture74.title = "Keep my commandments"
    scripture74.volume = "nt"
    scripture74.book = "john"
    scripture74.chapter = 14
    scripture74.verse = "15"
    scripture74.favorite = false
    scripture74.random = Int64(arc4random_uniform(1000))
    scripture74.selected = false
    scripture74.sortingIndex = 0
    scripture74.alphabet = String(describing: scripture74.title![(scripture74.title!.startIndex)])
    scripture74.order = Int64(defaultScriptureDictionary["\(scripture74.book!)"]!)
    
    let scripture102 = Scripture(context: context)
    scripture102.topic = "Heavenly Father"
    scripture102.title = "God so loved the world!"
    scripture102.volume = "nt"
    scripture102.book = "john"
    scripture102.chapter = 3
    scripture102.verse = "16"
    scripture102.favorite = true
    scripture102.random = Int64(arc4random_uniform(1000))
    scripture102.selected = true
    scripture102.sortingIndex = 0
    scripture102.alphabet = String(describing: scripture74.title![(scripture74.title!.startIndex)])
    scripture102.order = Int64(defaultScriptureDictionary["\(scripture74.book!)"]!)
    scripture102.selectedOne = taskScripture
    
    let scripture75 = Scripture(context: context)
    scripture75.topic = "Jesus Christ"
    scripture75.title = "The way, the truth, and the life"
    scripture75.volume = "nt"
    scripture75.book = "john"
    scripture75.chapter = 14
    scripture75.verse = "6"
    scripture75.favorite = false
    scripture75.random = Int64(arc4random_uniform(1000))
    scripture75.selected = false
    scripture75.sortingIndex = 0
    scripture75.alphabet = String(describing: scripture75.title![(scripture75.title!.startIndex)])
    scripture75.order = Int64(defaultScriptureDictionary["\(scripture75.book!)"]!)
    
    let scripture76 = Scripture(context: context)
    scripture76.topic = "Plan of Salvation"
    scripture76.title = "Know God and Jesus Christ"
    scripture76.volume = "nt"
    scripture76.book = "john"
    scripture76.chapter = 17
    scripture76.verse = "3"
    scripture76.favorite = false
    scripture76.random = Int64(arc4random_uniform(1000))
    scripture76.selected = false
    scripture76.sortingIndex = 0
    scripture76.alphabet = String(describing: scripture76.title![(scripture76.title!.startIndex)])
    scripture76.order = Int64(defaultScriptureDictionary["\(scripture76.book!)"]!)
    
    let scripture77 = Scripture(context: context)
    scripture77.topic = "Principles & Ordinances"
    scripture77.title = "Baptism"
    scripture77.volume = "nt"
    scripture77.book = "john"
    scripture77.chapter = 3
    scripture77.verse = "5"
    scripture77.favorite = false
    scripture77.random = Int64(arc4random_uniform(1000))
    scripture77.selected = false
    scripture77.sortingIndex = 0
    scripture77.alphabet = String(describing: scripture77.title![(scripture77.title!.startIndex)])
    scripture77.order = Int64(defaultScriptureDictionary["\(scripture77.book!)"]!)
    
    let scripture78 = Scripture(context: context)
    scripture78.topic = "Christlike Attributes"
    scripture78.title = "Serve the Lord"
    scripture78.volume = "ot"
    scripture78.book = "josh"
    scripture78.chapter = 24
    scripture78.verse = "15"
    scripture78.favorite = false
    scripture78.random = Int64(arc4random_uniform(1000))
    scripture78.selected = false
    scripture78.sortingIndex = 0
    scripture78.alphabet = String(describing: scripture78.title![(scripture78.title!.startIndex)])
    scripture78.order = Int64(defaultScriptureDictionary["\(scripture78.book!)"]!)
    
    let scripture79 = Scripture(context: context)
    scripture79.topic = "Jesus Christ"
    scripture79.title = "The First Vision"
    scripture79.volume = "pgp"
    scripture79.book = "js-h"
    scripture79.chapter = 1
    scripture79.verse = "15-20"
    scripture79.favorite = false
    scripture79.random = Int64(arc4random_uniform(1000))
    scripture79.selected = false
    scripture79.sortingIndex = 0
    scripture79.alphabet = String(describing: scripture79.title![(scripture79.title!.startIndex)])
    scripture79.order = Int64(defaultScriptureDictionary["\(scripture79.book!)"]!)
    
    let scripture80 = Scripture(context: context)
    scripture80.topic = "Plan of Salvation"
    scripture80.title = "Spirit hath not flesh and bones"
    scripture80.volume = "nt"
    scripture80.book = "luke"
    scripture80.chapter = 24
    scripture80.verse = "36-39"
    scripture80.favorite = false
    scripture80.random = Int64(arc4random_uniform(1000))
    scripture80.selected = false
    scripture80.sortingIndex = 0
    scripture80.alphabet = String(describing: scripture80.title![(scripture80.title!.startIndex)])
    scripture80.order = Int64(defaultScriptureDictionary["\(scripture80.book!)"]!)
    
    let scripture81 = Scripture(context: context)
    scripture81.topic = "Commandments"
    scripture81.title = "Tithes and offerings"
    scripture81.volume = "ot"
    scripture81.book = "mal"
    scripture81.chapter = 3
    scripture81.verse = "8-10"
    scripture81.favorite = false
    scripture81.random = Int64(arc4random_uniform(1000))
    scripture81.selected = false
    scripture81.sortingIndex = 0
    scripture81.alphabet = String(describing: scripture81.title![(scripture81.title!.startIndex)])
    scripture81.order = Int64(defaultScriptureDictionary["\(scripture81.book!)"]!)
    
    let scripture82 = Scripture(context: context)
    scripture82.topic = "Redeem the Dead"
    scripture82.title = "Spirit of Elijah"
    scripture82.volume = "ot"
    scripture82.book = "mal"
    scripture82.chapter = 4
    scripture82.verse = "5-6"
    scripture82.favorite = false
    scripture82.random = Int64(arc4random_uniform(1000))
    scripture82.selected = false
    scripture82.sortingIndex = 0
    scripture82.alphabet = String(describing: scripture82.title![(scripture82.title!.startIndex)])
    scripture82.order = Int64(defaultScriptureDictionary["\(scripture82.book!)"]!)

    let scripture83 = Scripture(context: context)
    scripture83.topic = "Jesus Christ"
    scripture83.title = "I will give you rest"
    scripture83.volume = "nt"
    scripture83.book = "matt"
    scripture83.chapter = 11
    scripture83.verse = "28-30"
    scripture83.favorite = true
    scripture83.random = Int64(arc4random_uniform(1000))
    scripture83.selected = false
    scripture83.sortingIndex = 0
    scripture83.alphabet = String(describing: scripture83.title![(scripture83.title!.startIndex)])
    scripture83.order = Int64(defaultScriptureDictionary["\(scripture83.book!)"]!)

    let scripture84 = Scripture(context: context)
    scripture84.topic = "Restoration"
    scripture84.title = "Keys to bind in heaven"
    scripture84.volume = "nt"
    scripture84.book = "matt"
    scripture84.chapter = 16
    scripture84.verse = "15-19"
    scripture84.favorite = false
    scripture84.random = Int64(arc4random_uniform(1000))
    scripture84.selected = false
    scripture84.sortingIndex = 0
    scripture84.alphabet = String(describing: scripture84.title![(scripture84.title!.startIndex)])
    scripture84.order = Int64(defaultScriptureDictionary["\(scripture84.book!)"]!)

    let scripture85 = Scripture(context: context)
    scripture85.topic = "Commandments"
    scripture85.title = "Love God and neighbor"
    scripture85.volume = "nt"
    scripture85.book = "matt"
    scripture85.chapter = 22
    scripture85.verse = "36-39"
    scripture85.favorite = true
    scripture85.random = Int64(arc4random_uniform(1000))
    scripture85.selected = false
    scripture85.sortingIndex = 0
    scripture85.alphabet = String(describing: scripture85.title![(scripture85.title!.startIndex)])
    scripture85.order = Int64(defaultScriptureDictionary["\(scripture85.book!)"]!)

    let scripture86 = Scripture(context: context)
    scripture86.topic = "Proclaim the Gospel"
    scripture86.title = "Teach all nations"
    scripture86.volume = "nt"
    scripture86.book = "matt"
    scripture86.chapter = 28
    scripture86.verse = "19-20"
    scripture86.favorite = false
    scripture86.random = Int64(arc4random_uniform(1000))
    scripture86.selected = false
    scripture86.sortingIndex = 0
    scripture86.alphabet = String(describing: scripture86.title![(scripture86.title!.startIndex)])
    scripture86.order = Int64(defaultScriptureDictionary["\(scripture86.book!)"]!)
    
    let scripture87 = Scripture(context: context)
    scripture87.topic = "Care for the Poor & Needy"
    scripture87.title = "Let your light so shine"
    scripture87.volume = "nt"
    scripture87.book = "matt"
    scripture87.chapter = 5
    scripture87.verse = "14-16"
    scripture87.favorite = false
    scripture87.random = Int64(arc4random_uniform(1000))
    scripture87.selected = false
    scripture87.sortingIndex = 0
    scripture87.alphabet = String(describing: scripture87.title![(scripture87.title!.startIndex)])
    scripture87.order = Int64(defaultScriptureDictionary["\(scripture87.book!)"]!)

    let scripture88 = Scripture(context: context)
    scripture88.topic = "Holy Ghost"
    scripture88.title = "Truth of all things"
    scripture88.volume = "bofm"
    scripture88.book = "moro"
    scripture88.chapter = 10
    scripture88.verse = "4-5"
    scripture88.favorite = true
    scripture88.random = Int64(arc4random_uniform(1000))
    scripture88.selected = false
    scripture88.sortingIndex = 0
    scripture88.alphabet = String(describing: scripture88.title![(scripture88.title!.startIndex)])
    scripture88.order = Int64(defaultScriptureDictionary["\(scripture88.book!)"]!)

    let scripture89 = Scripture(context: context)
    scripture89.topic = "Atonement"
    scripture89.title = "Raised unto life eternal"
    scripture89.volume = "bofm"
    scripture89.book = "moro"
    scripture89.chapter = 7
    scripture89.verse = "41"
    scripture89.favorite = false
    scripture89.random = Int64(arc4random_uniform(1000))
    scripture89.selected = false
    scripture89.sortingIndex = 0
    scripture89.alphabet = String(describing: scripture89.title![(scripture89.title!.startIndex)])
    scripture89.order = Int64(defaultScriptureDictionary["\(scripture89.book!)"]!)

    let scripture90 = Scripture(context: context)
    scripture90.topic = "Christlike Attributes"
    scripture90.title = "Charity"
    scripture90.volume = "bofm"
    scripture90.book = "moro"
    scripture90.chapter = 7
    scripture90.verse = "45-48"
    scripture90.favorite = true
    scripture90.random = Int64(arc4random_uniform(1000))
    scripture90.selected = false
    scripture90.sortingIndex = 0
    scripture90.alphabet = String(describing: scripture90.title![(scripture90.title!.startIndex)])
    scripture90.order = Int64(defaultScriptureDictionary["\(scripture90.book!)"]!)

    let scripture91 = Scripture(context: context)
    scripture91.topic = "Heavenly Father"
    scripture91.title = "God’s work and glory"
    scripture91.volume = "pgp"
    scripture91.book = "moses"
    scripture91.chapter = 1
    scripture91.verse = "39"
    scripture91.favorite = false
    scripture91.random = Int64(arc4random_uniform(1000))
    scripture91.selected = false
    scripture91.sortingIndex = 0
    scripture91.alphabet = String(describing: scripture91.title![(scripture91.title!.startIndex)])
    scripture91.order = Int64(defaultScriptureDictionary["\(scripture91.book!)"]!)

    let scripture92 = Scripture(context: context)
    scripture92.topic = "Restoration"
    scripture92.title = "Zion"
    scripture92.volume = "pgp"
    scripture92.book = "moses"
    scripture92.chapter = 7
    scripture92.verse = "18"
    scripture92.favorite = false
    scripture92.random = Int64(arc4random_uniform(1000))
    scripture92.selected = false
    scripture92.sortingIndex = 0
    scripture92.alphabet = String(describing: scripture92.title![(scripture92.title!.startIndex)])
    scripture92.order = Int64(defaultScriptureDictionary["\(scripture92.book!)"]!)

    let scripture93 = Scripture(context: context)
    scripture93.topic = "Care for the Poor & Needy"
    scripture93.title = "Service of your fellow beings"
    scripture93.volume = "bofm"
    scripture93.book = "mosiah"
    scripture93.chapter = 2
    scripture93.verse = "17"
    scripture93.favorite = false
    scripture93.random = Int64(arc4random_uniform(1000))
    scripture93.selected = false
    scripture93.sortingIndex = 0
    scripture93.alphabet = String(describing: scripture93.title![(scripture93.title!.startIndex)])
    scripture93.order = Int64(defaultScriptureDictionary["\(scripture93.book!)"]!)

    let scripture94 = Scripture(context: context)
    scripture94.topic = "Endure to the end"
    scripture94.title = "Natural man"
    scripture94.volume = "bofm"
    scripture94.book = "mosiah"
    scripture94.chapter = 3
    scripture94.verse = "19"
    scripture94.favorite = true
    scripture94.random = Int64(arc4random_uniform(1000))
    scripture94.selected = false
    scripture94.sortingIndex = 0
    scripture94.alphabet = String(describing: scripture94.title![(scripture94.title!.startIndex)])
    scripture94.order = Int64(defaultScriptureDictionary["\(scripture94.book!)"]!)

    let scripture95 = Scripture(context: context)
    scripture95.topic = "Christlike Attributes"
    scripture95.title = "Thoughts, words, and deeds"
    scripture95.volume = "bofm"
    scripture95.book = "mosiah"
    scripture95.chapter = 4
    scripture95.verse = "30"
    scripture95.favorite = false
    scripture95.random = Int64(arc4random_uniform(1000))
    scripture95.selected = false
    scripture95.sortingIndex = 0
    scripture95.alphabet = String(describing: scripture95.title![(scripture95.title!.startIndex)])
    scripture95.order = Int64(defaultScriptureDictionary["\(scripture95.book!)"]!)

    let scripture96 = Scripture(context: context)
    scripture96.topic = "Jesus Christ"
    scripture96.title = "All things through Christ"
    scripture96.volume = "nt"
    scripture96.book = "philip"
    scripture96.chapter = 4
    scripture96.verse = "13"
    scripture96.favorite = false
    scripture96.random = Int64(arc4random_uniform(1000))
    scripture96.selected = false
    scripture96.sortingIndex = 0
    scripture96.alphabet = String(describing: scripture96.title![(scripture96.title!.startIndex)])
    scripture96.order = Int64(defaultScriptureDictionary["\(scripture96.book!)"]!)

    let scripture97 = Scripture(context: context)
    scripture97.topic = "Christlike Attributes"
    scripture97.title = "Trust in the Lord"
    scripture97.volume = "ot"
    scripture97.book = "prov"
    scripture97.chapter = 3
    scripture97.verse = "5-6"
    scripture97.favorite = false
    scripture97.random = Int64(arc4random_uniform(1000))
    scripture97.selected = false
    scripture97.sortingIndex = 0
    scripture97.alphabet = String(describing: scripture97.title![(scripture97.title!.startIndex)])
    scripture97.order = Int64(defaultScriptureDictionary["\(scripture97.book!)"]!)

    let scripture98 = Scripture(context: context)
    scripture98.topic = "Heavenly Father"
    scripture98.title = "God’s word"
    scripture98.volume = "ot"
    scripture98.book = "ps"
    scripture98.chapter = 119
    scripture98.verse = "105"
    scripture98.favorite = false
    scripture98.random = Int64(arc4random_uniform(1000))
    scripture98.selected = false
    scripture98.sortingIndex = 0
    scripture98.alphabet = String(describing: scripture98.title![(scripture98.title!.startIndex)])
    scripture98.order = Int64(defaultScriptureDictionary["\(scripture98.book!)"]!)
    
    let scripture99 = Scripture(context: context)
    scripture99.topic = "Heavenly Father"
    scripture99.title = "Heritage of the Lord"
    scripture99.volume = "ot"
    scripture99.book = "ps"
    scripture99.chapter = 127
    scripture99.verse = "3"
    scripture99.favorite = false
    scripture99.random = Int64(arc4random_uniform(1000))
    scripture99.selected = false
    scripture99.sortingIndex = 0
    scripture99.alphabet = String(describing: scripture99.title![(scripture99.title!.startIndex)])
    scripture99.order = Int64(defaultScriptureDictionary["\(scripture99.book!)"]!)

    let scripture100 = Scripture(context: context)
    scripture100.topic = "Christlike Attributes"
    scripture100.title = "Clean hands and a pure heart"
    scripture100.volume = "ot"
    scripture100.book = "ps"
    scripture100.chapter = 24
    scripture100.verse = "3-4"
    scripture100.favorite = false
    scripture100.random = Int64(arc4random_uniform(1000))
    scripture100.selected = false
    scripture100.sortingIndex = 0
    scripture100.alphabet = String(describing: scripture100.title![(scripture100.title!.startIndex)])
    scripture100.order = Int64(defaultScriptureDictionary["\(scripture100.book!)"]!)

    let scripture101 = Scripture(context: context)
    scripture101.topic = "Scriptures"
    scripture101.title = "Judged from scriptures"
    scripture101.volume = "nt"
    scripture101.book = "rev"
    scripture101.chapter = 20
    scripture101.verse = "12"
    scripture101.favorite = false
    scripture101.random = Int64(arc4random_uniform(1000))
    scripture101.selected = false
    scripture101.sortingIndex = 0
    scripture101.alphabet = String(describing: scripture101.title![(scripture101.title!.startIndex)])
    scripture101.order = Int64(defaultScriptureDictionary["\(scripture101.book!)"]!)

    ad.saveContext()
}
